reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false

exclude:
 - package.json
 - gulpfile.js
 - node_modules
 - sass

future: true

social-links:
 - name: mail
   href: //mail.ru
 - name: vk
   href: //vk.com
 - name: instagram
   href: //instagram.com
 - name: twitter
   href: //twitter.com